export const REMOVE_ALL = "REMOVE_ALL";

/**
 * USER
 */

export const SET_USER = "SET_USER";
export const REMOVE_USER = "REMOVE_USER";

/**
 * ALERT
 */

export const SET_ALERT = "SET_ALERT";

/**
 * PANEL USERS
 */

export const SET_PANEL_USERS = "SET_PANEL_USERS";
export const REMOVE_PANEL_USERS = "REMOVE_PANEL_USERS";

/**
 * PANEL EXERCISES
 */

export const SET_PANEL_VERIFIED_EXERCISES = "SET_PANEL_VERIFIED_EXERCISES";
export const SET_PANEL_UNVERIFIED_EXERCISES = "SET_PANEL_UNVERIFIED_EXERCISES";

export const REMOVE_PANEL_EXERCISES = "REMOVE_PANEL_EXERCISES";

/**
 * SET COACHES
 */

export const SET_COACHES = "SET_COACHES";
export const REMOVE_COACHES = "REMOVE_COACHES";
